# ===================== CREACIÓN DE USUARIOS Y LOGIN ===================== #

### Registro de usuario básico
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
    "nombre": "Daniel",
    "email": "daniel@gmail.com",
    "password": "qwertyui",
    "edad": 19,
    "ciudad": "Madrid",
    "intereses": ["cine", "música"],
    "permiteRecibirOfertas": true
}

### Login de usuario básico
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "email": "daniel@gmail.com",
    "password": "qwertyui"
}

### Registro de usuario admin (acuerdate de cambiar el rol en la BBDD)
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
    "nombre": "Administrador",
    "email": "admin@example.com",
    "password": "Admin1234",
    "edad": 30,
    "ciudad": "Madrid",
    "intereses": ["lectura", "deporte"]
}

### Inicia sesión como administrador
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "Admin1234"
}

### Creación de usuario merchant (solo el admin)
POST http://localhost:3000/api/user/register-merchant
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzQ0NTU0NGE4MTBlZTNlYzYwZTlkMWQiLCJyb2xlIjoidXNlciIsImlhdCI6MTczMjUzMTc3MSwiZXhwIjoxNzMyNTM4OTcxfQ.pOpHbqr1pNrDa_Kg9Kbs1ieTPQHXECtOf_ERc-hbhTI
Content-Type: application/json

{
    "nombre": "Comercia XYZ",
    "email": "comercioxyz@example.com",
    "password": "Password123",
    "edad": 35,
    "ciudad": "Madrid"
}

### Login del merchant
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "email": "comercioxyz@example.com",
    "password": "Password123"
}

# ===================== OPERACIONES CON USUARIOS ===================== #

### Modificar datos del usuario básico (requiere token)
PUT http://localhost:3000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzQ0M2RmNjJiNjdmNDc3MTJhODYwNTkiLCJyb2xlIjoidXNlciIsImlhdCI6MTczMjUyNTc4OCwiZXhwIjoxNzMyNTMyOTg4fQ.G4yK4xjRqjLGinfmnn2pJiJg0Li2KvVqqZ-Psrc9T_I
Content-Type: application/json

{
    "nombre": "Usuario Básico Modificado",
    "ciudad": "Barcelona"
}

### Eliminar usuario (requiere token)
DELETE http://localhost:3000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzQ0M2Y2YzJiNjdmNDc3MTJhODYwNmEiLCJyb2xlIjoidXNlciIsImlhdCI6MTczMjUyNjUyMiwiZXhwIjoxNzMyNTMzNzIyfQ.1aXdziTuWM8j9tfsI7THnuVCg0cfig1yJjcldCfHvio
Content-Type: application/json

### Obtener correos de usuarios interesados
GET http://localhost:3000/api/store/interested-users?topic=cine
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzQ0M2U4MTJiNjdmNDc3MTJhODYwNjAiLCJyb2xlIjoibWVyY2hhbnQiLCJpYXQiOjE3MzI1MjU3MTQsImV4cCI6MTczMjUzMjkxNH0.aFlwy0_mXSHog4CSplzD9HvJknpu0eyFJ6MYcb9-Muc
Content-Type: application/json

# ===================== OPERACIONES CON COMERCIO ===================== #


### Añadir comercio (solo accesible por admin)
POST http://localhost:3000/api/store
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzQ0NTU0NGE4MTBlZTNlYzYwZTlkMWQiLCJyb2xlIjoidXNlciIsImlhdCI6MTczMjUzMTc3MSwiZXhwIjoxNzMyNTM4OTcxfQ.pOpHbqr1pNrDa_Kg9Kbs1ieTPQHXECtOf_ERc-hbhTI
Content-Type: application/json

{
    "storeName": "Tienda Animales",
    "CIF": "A23523",
    "address": "Calle Mirasuegros 33, Madrid",
    "email": "contacto@tiendaanimales.com",
    "contactNumber": "+34 632 252 234",
    "merchantId": "67445668a810ee3ec60e9d2b"
}

### Obtener todos los comercios
GET http://localhost:3000/api/store?order=true
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzQ0NTU0NGE4MTBlZTNlYzYwZTlkMWQiLCJyb2xlIjoidXNlciIsImlhdCI6MTczMjUzMTc3MSwiZXhwIjoxNzMyNTM4OTcxfQ.pOpHbqr1pNrDa_Kg9Kbs1ieTPQHXECtOf_ERc-hbhTI
Content-Type: application/json

### Obtener un comercio específico por su CIF
GET http://localhost:3000/api/store/B12345678
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzQ0NTU0NGE4MTBlZTNlYzYwZTlkMWQiLCJyb2xlIjoidXNlciIsImlhdCI6MTczMjUzMTc3MSwiZXhwIjoxNzMyNTM4OTcxfQ.pOpHbqr1pNrDa_Kg9Kbs1ieTPQHXECtOf_ERc-hbhTI
Content-Type: application/json

### Modificar comercio por CIF (solo accesible por admin)
PUT http://localhost:3000/api/store/A23523
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzQ0NTU0NGE4MTBlZTNlYzYwZTlkMWQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzI1MzI0MTAsImV4cCI6MTczMjUzOTYxMH0.BJNJLTepvb1kIpaFNlP--phkkzL5eVAvB1_rvFIe_h8
Content-Type: application/json

{
  "adress": "Avenida del Comercio, 150, Barcelona",
  "contactNumber": "+34 600 123 789",
  "merchantId": "67445668a810ee3ec60e9d2b"
}

### Eliminar comercio por CIF [Borrado Lógico]
DELETE http://localhost:3000/api/store/A23523?deleteType=logical
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzQzNWY0YmE0Zjc5MTgzN2E4NTJmYmQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzI0NjkyNDIsImV4cCI6MTczMjQ3NjQ0Mn0.XcIHg1wuS54iBLVKCcqx91xztynuKBaHpKpI-zxxLhY
Content-Type: application/json

# ===================== GESTIÓN DE PÁGINA WEB DE COMERCIO ===================== #

### Crear una página web de comercio (solo accesible por el merchant)
POST http://localhost:3000/api/webStore
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzQ0NTY2OGE4MTBlZTNlYzYwZTlkMmIiLCJyb2xlIjoibWVyY2hhbnQiLCJpYXQiOjE3MzI1MzI0NDYsImV4cCI6MTczMjUzOTY0Nn0.UKHFB2RW9GCb_qDft5hKfEV5DLKaxX5bHZL6bxjwsk8
Content-Type: application/json

{
    "city": "Madrid",
    "activity": "Mascotas",
    "title": "Tienda Animales",
    "resume": "Las mejores mascotas.",
    "textsArray": ["Mascotas especiales", "Mascotas"],
    "imagesArray": ["http://example.com/mascotin1.jpg", "http://example.com/animalia.jpg"],
    "reviews": {
        "scoring": 4.9,
        "totalRatings": 25,
        "reviews": ["Excelentes animales", "Buen servicio"]
    },
    "storeId": "53453"
}

### Obtener todas las páginas web de comercio
GET http://localhost:3000/api/webStore

### Obtener todas las páginas web de comercio de una ciudad
GET http://localhost:3000/api/webStore?city=Madrid

### Obtener todas las páginas web de comercio por ciudad y actividad
GET http://localhost:3000/api/webStore?city=Madrid?activity=Mascotas

### Obtener página web de comercio por su id
GET http://localhost:3000/api/webStore/67445eb0bf6d9f7e92430f94

### Añadir review (usuarios registrados)
PATCH http://localhost:3000/api/webStore/67445eb0bf6d9f7e92430f94/review
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzQ0NTY2OGE4MTBlZTNlYzYwZTlkMmIiLCJyb2xlIjoibWVyY2hhbnQiLCJpYXQiOjE3MzI1MzM1MTEsImV4cCI6MTczMjU0MDcxMX0.sEXVEEMrx_s3cQPBziM3ln8c83UYY7MhmMUCusUG-hQ
Content-Type: application/json

{
    "scoring": 4.5,
    "review": "Excelente servicio y productos de calidad."
}

### Modificar una página web por su id (solo accesible por el comercio propietario)
PUT http://localhost:3000/api/webStore/67445eb0bf6d9f7e92430f94
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzQ0NTY2OGE4MTBlZTNlYzYwZTlkMmIiLCJyb2xlIjoibWVyY2hhbnQiLCJpYXQiOjE3MzI1MzM1MTEsImV4cCI6MTczMjU0MDcxMX0.sEXVEEMrx_s3cQPBziM3ln8c83UYY7MhmMUCusUG-hQ
Content-Type: application/json

{
  "city": "Barcelona",
  "title": "Tech Store Barcelona"
}

### Subir imagen a la página web (solo accesible por el comercio propietario)
PATCH http://localhost:3000/api/webStore/67445eb0bf6d9f7e92430f94/uploadImage
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzQ0NTY2OGE4MTBlZTNlYzYwZTlkMmIiLCJyb2xlIjoibWVyY2hhbnQiLCJpYXQiOjE3MzI1MzM1MTEsImV4cCI6MTczMjU0MDcxMX0.sEXVEEMrx_s3cQPBziM3ln8c83UYY7MhmMUCusUG-hQ
Content-Type: multipart/form-data; boundary=Boundry

--Boundry
Content-Disposition: form-data; name="image"; filename="doraemon.jpg"
Content-Type: image/jpg

< ./doraemon.jpg
--Boundry--

### Añadir texto a una web por su id (solo accesible por el comercio propietario)
POST http://localhost:3000/api/webStore/67445eb0bf6d9f7e92430f94/addText
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzQ0NTY2OGE4MTBlZTNlYzYwZTlkMmIiLCJyb2xlIjoibWVyY2hhbnQiLCJpYXQiOjE3MzI1MzM1MTEsImV4cCI6MTczMjU0MDcxMX0.sEXVEEMrx_s3cQPBziM3ln8c83UYY7MhmMUCusUG-hQ
Content-Type: application/json

{
    "text": "Este es un nuevo texto para mi página web."
}

### Eliminar una página web de comercio por Id [Borrado Físico]
DELETE http://localhost:3000/api/webStore/674457b7a810ee3ec60e9d3b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzQ0NTY2OGE4MTBlZTNlYzYwZTlkMmIiLCJyb2xlIjoibWVyY2hhbnQiLCJpYXQiOjE3MzI1MzM1MTEsImV4cCI6MTczMjU0MDcxMX0.sEXVEEMrx_s3cQPBziM3ln8c83UYY7MhmMUCusUG-hQ
Content-Type: application/json